apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: certificate
spec:
  commonName: rama-sweets.freeboxos.fr
  secretName: cert
  dnsNames:
    - rama-sweets.freeboxos.fr
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
