apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
    statefulset.kubernetes.io/pod-name: mongo-0
  name: mongo-0
  namespace: databases
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo
    statefulset.kubernetes.io/pod-name: mongo-0
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
    statefulset.kubernetes.io/pod-name: mongo-1
  name: mongo-1
  namespace: databases
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo
    statefulset.kubernetes.io/pod-name: mongo-1
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
    statefulset.kubernetes.io/pod-name: mongo-2
  name: mongo-2
  namespace: databases
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo
    statefulset.kubernetes.io/pod-name: mongo-2
  type: LoadBalancer
