apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mr-market-product-deployment
  name: mr-market-product-deployment
  namespace: mr-market
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mr-market-product-deployment
  template:
    metadata:
      labels:
        app: mr-market-product-deployment
    spec:
      containers:
        - image: reklaabderrahim/mr-market-product:latest
          name: mr-market-product
---
apiVersion: v1
kind: Service
metadata:
  name: mr-market-product-service
  namespace: mr-market
spec:
  selector:
    app: mr-market-product-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082