apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-db-disk
  labels:
    type: local
  namespace: databases
spec:
  storageClassName: "manuel"
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
#  claimRef:
#    name: postgresql-db-disk-claim
#    namespace: gosra_auto
  nfs:
    path: "/srv/nfs/kubedata/var/lib/pgadmin"
    server: 192.168.1.12