# PostgreSQL StatefulSet ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-config
  namespace: databases
  labels:
    app: postgresql-db
data:
  POSTGRES_PASSWORD: customerOwner
  POSTGRES_USER: customerOwner
  POSTGRES_DB: customer
  PGDATA: /data/pgdata