apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-db-disk-01
  labels:
    type: local
  namespace: databases
spec:
  storageClassName: "manuel"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
#  claimRef:
#    name: postgresql-db-disk-claim
#    namespace: gosra_auto
  nfs:
    path: "/srv/nfs/kubedata/data"
    server: 192.168.1.12
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-db-disk-02
  labels:
    type: local
  namespace: databases
spec:
  storageClassName: "manuel"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  #  claimRef:
  #    name: postgresql-db-disk-claim
  #    namespace: gosra_auto
  nfs:
    path: "/srv/nfs/kubedata/data"
    server: 192.168.1.12